# Generated by Django 5.0.6 on 2024-07-15 01:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RelatedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Models",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("big_integer_field", models.BigIntegerField()),
                ("binary_field", models.BinaryField()),
                ("boolean_field", models.BooleanField()),
                ("char_field", models.CharField(max_length=100)),
                ("date_field", models.DateField()),
                ("date_time_field", models.DateTimeField()),
                ("decimal_field", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration_field", models.DurationField()),
                ("email_field", models.EmailField(max_length=254)),
                ("file_field", models.FileField(upload_to="uploads/")),
                ("file_field_and_field_file", models.FileField(upload_to="uploads/")),
                ("file_path_field", models.FilePathField(path="/var/www/media/")),
                ("float_field", models.FloatField()),
                (
                    "generated_field",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("generic_ip_address_field", models.GenericIPAddressField()),
                ("image_field", models.ImageField(upload_to="images/")),
                ("integer_field", models.IntegerField()),
                ("json_field", models.JSONField()),
                ("positive_big_integer_field", models.PositiveBigIntegerField()),
                ("positive_integer_field", models.PositiveIntegerField()),
                ("positive_small_integer_field", models.PositiveSmallIntegerField()),
                ("slug_field", models.SlugField()),
                ("small_integer_field", models.SmallIntegerField()),
                ("text_field", models.TextField()),
                ("time_field", models.TimeField()),
                ("url_field", models.URLField()),
                (
                    "uuid_field",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "foreign_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models_foreign_keys",
                        to="models.relatedmodel",
                    ),
                ),
                (
                    "many_to_many_field",
                    models.ManyToManyField(
                        related_name="models_many_to_many", to="models.relatedmodel"
                    ),
                ),
                (
                    "one_to_one_field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models_one_to_ones",
                        to="models.relatedmodel",
                    ),
                ),
            ],
        ),
    ]
